ALTER TABLE class_groups
  ADD COLUMN IF NOT EXISTS capacity INT NOT NULL DEFAULT 30;

ALTER TABLE class_groups
  DROP CONSTRAINT IF EXISTS class_groups_capacity_check;

ALTER TABLE class_groups
  ADD CONSTRAINT class_groups_capacity_check CHECK (capacity BETWEEN 1 AND 200);

CREATE TABLE IF NOT EXISTS class_group_enrollments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id UUID NOT NULL REFERENCES students(id),
  class_group_id UUID NOT NULL REFERENCES class_groups(id),
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ends_at TIMESTAMPTZ,
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  withdrawal_reason TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT class_group_enrollments_student_group_unique UNIQUE(student_id, class_group_id),
  CONSTRAINT class_group_enrollments_status_check CHECK (
    status IN ('active','waitlisted','trial','frozen','withdrawn','completed')
  ),
  CONSTRAINT class_group_enrollments_dates_check CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

CREATE INDEX IF NOT EXISTS idx_class_group_enrollments_group_status
  ON class_group_enrollments(class_group_id, status);

CREATE INDEX IF NOT EXISTS idx_class_group_enrollments_student_status
  ON class_group_enrollments(student_id, status);

ALTER TABLE class_sessions
  ADD COLUMN IF NOT EXISTS attendance_state VARCHAR(20) NOT NULL DEFAULT 'draft';

ALTER TABLE class_sessions
  DROP CONSTRAINT IF EXISTS class_sessions_attendance_state_check;

ALTER TABLE class_sessions
  ADD CONSTRAINT class_sessions_attendance_state_check CHECK (attendance_state IN ('draft','finalized'));

ALTER TABLE class_sessions
  DROP CONSTRAINT IF EXISTS class_sessions_dates_check;

ALTER TABLE class_sessions
  ADD CONSTRAINT class_sessions_dates_check CHECK (ends_at > starts_at);

ALTER TABLE student_attendance_records
  ADD COLUMN IF NOT EXISTS recorded_by UUID REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS correction_reason TEXT,
  ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

INSERT INTO absence_justifications (
  attendance_record_id,
  reason,
  status,
  review_notes,
  reviewed_at
)
SELECT
  attendance.id,
  'Legacy justified attendance migrated to an approved absence justification.',
  'approved',
  'Generated by migration 005 to preserve the historical excuse decision.',
  now()
FROM student_attendance_records attendance
WHERE attendance.status = 'justified'
  AND NOT EXISTS (
    SELECT 1
    FROM absence_justifications justification
    WHERE justification.attendance_record_id = attendance.id
      AND justification.status = 'approved'
  );

UPDATE student_attendance_records
SET status = 'absent'
WHERE status = 'justified' OR status IS NULL;

ALTER TABLE student_attendance_records
  ALTER COLUMN status SET NOT NULL;

ALTER TABLE student_attendance_records
  DROP CONSTRAINT IF EXISTS student_attendance_records_status_check;

ALTER TABLE student_attendance_records
  ADD CONSTRAINT student_attendance_records_status_check CHECK (status IN ('present','absent','late'));

ALTER TABLE student_attendance_records
  DROP CONSTRAINT IF EXISTS student_attendance_records_version_check;

ALTER TABLE student_attendance_records
  ADD CONSTRAINT student_attendance_records_version_check CHECK (version >= 1);

WITH ranked AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY attendance_record_id
      ORDER BY CASE WHEN status = 'approved' THEN 0 ELSE 1 END, reviewed_at DESC NULLS LAST, id
    ) AS row_number
  FROM absence_justifications
  WHERE status IN ('pending','approved')
)
UPDATE absence_justifications justification
SET
  status = 'rejected',
  review_notes = CONCAT_WS(' ', justification.review_notes, 'Rejected by migration 005 because another active justification exists.'),
  reviewed_at = COALESCE(justification.reviewed_at, now())
FROM ranked
WHERE ranked.id = justification.id
  AND ranked.row_number > 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_absence_justifications_one_active
  ON absence_justifications(attendance_record_id)
  WHERE status IN ('pending','approved');

ALTER TABLE scholarship_rules
  ADD COLUMN IF NOT EXISTS minimum_sessions INT NOT NULL DEFAULT 8;

ALTER TABLE scholarship_rules
  DROP CONSTRAINT IF EXISTS scholarship_rules_minimum_sessions_check;

ALTER TABLE scholarship_rules
  ADD CONSTRAINT scholarship_rules_minimum_sessions_check CHECK (minimum_sessions >= 1);
