CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE branches (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(80) UNIQUE NOT NULL, city VARCHAR(80), active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(40) UNIQUE NOT NULL);
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), code VARCHAR(80) UNIQUE NOT NULL, description TEXT);
CREATE TABLE role_permissions (role_id UUID REFERENCES roles(id), permission_id UUID REFERENCES permissions(id), PRIMARY KEY(role_id, permission_id));
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), google_sub VARCHAR(160) UNIQUE, email VARCHAR(160) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, password_hash TEXT, role_id UUID REFERENCES roles(id), active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE user_branch_access (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id), branch_id UUID NOT NULL REFERENCES branches(id), created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(user_id, branch_id));
CREATE TABLE students (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), branch_id UUID NOT NULL REFERENCES branches(id), full_name VARCHAR(160) NOT NULL, level VARCHAR(2) CHECK(level IN ('B1','B2')), active BOOLEAN DEFAULT TRUE);
CREATE TABLE teachers (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), branch_id UUID REFERENCES branches(id), full_name VARCHAR(160) NOT NULL, hourly_rate NUMERIC(10,2) NOT NULL DEFAULT 12.50, active BOOLEAN DEFAULT TRUE);
CREATE TABLE dance_categories (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE dance_styles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), category_id UUID REFERENCES dance_categories(id), name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE teacher_styles (teacher_id UUID REFERENCES teachers(id), style_id UUID REFERENCES dance_styles(id), PRIMARY KEY(teacher_id, style_id));
CREATE TABLE class_groups (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), branch_id UUID REFERENCES branches(id), style_id UUID REFERENCES dance_styles(id), teacher_id UUID REFERENCES teachers(id), name VARCHAR(120) NOT NULL, level VARCHAR(2) CHECK(level IN ('B1','B2')), active BOOLEAN DEFAULT TRUE);
CREATE TABLE class_sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), class_group_id UUID REFERENCES class_groups(id), starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, status VARCHAR(20) DEFAULT 'scheduled');
CREATE TABLE student_attendance_records (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), student_id UUID REFERENCES students(id), class_session_id UUID REFERENCES class_sessions(id), status VARCHAR(20) CHECK(status IN ('present','absent','justified','late')), notes TEXT, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(student_id, class_session_id));
CREATE TABLE teacher_attendance_records (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), teacher_id UUID REFERENCES teachers(id), class_session_id UUID REFERENCES class_sessions(id), check_in_at TIMESTAMPTZ NOT NULL, check_out_at TIMESTAMPTZ);
CREATE TABLE absence_justifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), attendance_record_id UUID REFERENCES student_attendance_records(id), reason TEXT NOT NULL, evidence_url TEXT, status VARCHAR(20) DEFAULT 'pending', reviewed_by UUID REFERENCES users(id), review_notes TEXT, reviewed_at TIMESTAMPTZ);
CREATE TABLE scholarship_rules (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), min_attendance_percent NUMERIC(5,2) NOT NULL DEFAULT 90.00, period_months INT NOT NULL DEFAULT 2, active BOOLEAN DEFAULT TRUE);
CREATE TABLE scholarship_evaluations (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), student_id UUID REFERENCES students(id), percentage INT CHECK(percentage IN (25,50,75,100)), attendance_rate NUMERIC(5,2), theory_score NUMERIC(5,2), practice_score NUMERIC(5,2), approved BOOLEAN DEFAULT FALSE, evaluated_by UUID REFERENCES users(id), evaluated_at TIMESTAMPTZ);
CREATE TABLE level_promotion_evaluations (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), student_id UUID REFERENCES students(id), from_level VARCHAR(2), to_level VARCHAR(2), attendance_rate NUMERIC(5,2), consistency_score NUMERIC(5,2), theory_score NUMERIC(5,2), practice_score NUMERIC(5,2), approved BOOLEAN DEFAULT FALSE, evaluated_by UUID REFERENCES users(id), evaluated_at TIMESTAMPTZ);
CREATE TABLE enrollment_requests (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), full_name VARCHAR(160) NOT NULL, email VARCHAR(160) NOT NULL, phone VARCHAR(40), branch_id UUID REFERENCES branches(id), preferred_branch VARCHAR(80), style_interest VARCHAR(120), message TEXT, status VARCHAR(20) DEFAULT 'pending', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), token_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked BOOLEAN DEFAULT FALSE);
CREATE TABLE audit_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), actor_user_id UUID REFERENCES users(id), action VARCHAR(120) NOT NULL, entity VARCHAR(120) NOT NULL, entity_id UUID, metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_students_branch ON students(branch_id);
CREATE INDEX idx_user_branch_access_branch ON user_branch_access(branch_id);
CREATE INDEX idx_student_attendance_student ON student_attendance_records(student_id);
CREATE INDEX idx_teacher_attendance_teacher ON teacher_attendance_records(teacher_id);
CREATE INDEX idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_user_id);
