const { AppError } = require('../exceptions/AppError');
class AttendanceService {
  constructor(db, audit) { this.db = db; this.audit = audit; }
  async recordStudentAttendance(actor, data) { if (!(await this.db.students.findById(data.studentId))) throw new AppError('Student not found', 404); if (!(await this.db.classSessions.findById(data.classSessionId))) throw new AppError('Class session not found', 404); const rows = await this.db.studentAttendance.all(); if (rows.some((r) => r.studentId === data.studentId && r.classSessionId === data.classSessionId)) throw new AppError('Attendance already recorded for this student and session', 409); const record = await this.db.studentAttendance.create(data); await this.audit.log(actor.id, 'STUDENT_ATTENDANCE_RECORDED', 'student_attendance_records', record.id, { status:data.status }); return record; }
  async checkInTeacher(actor, data) { if (!(await this.db.teachers.findById(data.teacherId))) throw new AppError('Teacher not found', 404); if (data.classSessionId && !(await this.db.classSessions.findById(data.classSessionId))) throw new AppError('Class session not found', 404); const rows = await this.db.teacherAttendance.all(); if (rows.some((r) => r.teacherId === data.teacherId && !r.checkOutAt)) throw new AppError('Teacher already has an open check-in', 409); const record = await this.db.teacherAttendance.create({ ...data, checkInAt:new Date().toISOString(), checkOutAt:null }); await this.audit.log(actor.id, 'TEACHER_CHECK_IN', 'teacher_attendance_records', record.id); return record; }
  async checkOutTeacher(actor, recordId) { const record = await this.db.teacherAttendance.findById(recordId); if (!record) throw new AppError('Teacher attendance record not found', 404); if (record.checkOutAt) throw new AppError('Teacher attendance record already checked out', 409); const updated = await this.db.teacherAttendance.update(recordId, { checkOutAt:new Date().toISOString() }); await this.audit.log(actor.id, 'TEACHER_CHECK_OUT', 'teacher_attendance_records', recordId); return updated; }
  async attendanceRate(studentId, from, to) { const rows = (await this.db.studentAttendance.all()).filter((r) => r.studentId === studentId); const scoped = rows.filter((r) => { const date = new Date(r.createdAt || r.created_at || Date.now()); return (!from || date >= new Date(from)) && (!to || date <= new Date(to)); }); if (!scoped.length) return 0; return scoped.filter((r) => ['present','late','justified'].includes(r.status)).length / scoped.length; }
}
module.exports = { AttendanceService };
